# Generated by Django 5.2.6 on 2025-12-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='interests',
            field=models.CharField(blank=True, help_text='Comma separated interests (e.g. Reading, Music, Sports)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='level_preference',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('100', '100 Lvl'), ('200', '200 Lvl'), ('300', '300 Lvl'), ('400', '400 Lvl'), ('500', '500 Lvl')], max_length=10, null=True),
        ),
    ]
