# Generated by Django 5.2.6 on 2025-12-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_listing_gender_preference_listing_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='level_preference',
            field=models.CharField(blank=True, choices=[('100', '100 Lvl'), ('200', '200 Lvl'), ('300', '300 Lvl'), ('400', '400 Lvl'), ('500', '500 Lvl')], max_length=10, null=True),
        ),
    ]
