# Generated by Django 5.2.6 on 2025-12-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_listing_gender_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
