# Generated by Django

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_listingvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingVideo',
        ),
    ]
